### ISSUE TITLE
raise ValueError("Incompatible component merge:\n - %r\n - %r" ValueError: Incompatible component merge:      'mpich'     'mpi_mpich_*'

### ISSUE THREAD

**Issue by rangfeng1** [ompl/conda-recipes#1]
when use conda build -c conda-forge ompl
Solving environment: ...working... failed
Traceback (most recent call last):
File "/home/wxj/anaconda3/bin/conda-build", line 11, in
sys.exit(main())
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 496, in main
execute(sys.argv[1:])
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 485, in execute
outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
return build_tree(
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 3091, in build_tree
packages_from_this = build(metadata, stats,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 2054, in build
output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 788, in expand_outputs
for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/metadata.py", line 2121, in get_output_metadata_set
conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/metadata.py", line 782, in finalize_outputs_pass
fm = finalize_metadata(om, parent_metadata=parent_metadata,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 546, in finalize_metadata
build_unsat, host_unsat = add_upstream_pins(m,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 408, in add_upstream_pins
host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 373, in _read_upstream_pin_files
deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 138, in get_env_dependencies
actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda_build/environ.py", line 799, in get_install_actions
actions = install_actions(prefix, index, specs, force=True)
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
return f(*args, **kwds)
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/plan.py", line 476, in install_actions
txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 156, in solve_for_transaction
unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 199, in solve_for_diff
final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 317, in solve_final_state
ssc = self._add_specs(ssc)
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 711, in add_specs
conflicts = ssc.r.get_conflicting_specs(tuple(MatchSpec()
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 1110, in get_conflicting_specs
C = r2.gen_clauses()
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
return f(*args, **kwds)
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 913, in gen_clauses
for ms in self.ms_depends(prec):
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 797, in ms_depends
deps = [MatchSpec(d) for d in prec.combined_depends]
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/models/records.py", line 341, in combined_depends
result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 480, in merge
reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 480, in
reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 511, in _merge
final = this_component.merge(that_component)
File "/home/wxj/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 762, in merge
raise ValueError("Incompatible component merge:\n - %r\n - %r"
ValueError: Incompatible component merge:

    'mpich'
    'mpi_mpich_*'

**Comment by wbthomason** [comment]
Can you share your `conda` version? I've only tried this recipe with Python 3.10, but I did see this error at one point in the development process. I forget exactly what fixed it, but I think it had to do with a bug in some versions of `conda`.

**Comment by Xi-HHHM** [comment]
I noticed that Python 3.10 is specified in the `conda_build_config.yaml`, if I want to install ompl in a `conda` environment with Python 3.8, should I modify the configuration to 3.8?

**Comment by wbthomason** [comment]
Yes - though you will also need to change the Boost versions, and maybe other dependency versions. Those are specified in `meta.yaml`.
